# -*- coding: utf-8 -*-
"""ilk_ders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_LHavOSXhpdLGYTt_3pTSozECOAhn2M
"""

a=2+2
print(a)
a="Ahmet"
print(a)

""""+ Code" yardımıyla yeni kod bloğu eklendiğinde önceki kod bloklarındaki değişkenlerin değerleri saklanmaktadır."""

print(a)

""""Merhaba Dünya" ilk örnek...."""

a="Merhaba"
print(a)
a="Dünya"
print(a)

""""Merhaba Dünya" ikinci örnek"""

print("Merhaba \nDünya")

"""Kullanıcıdan girdi almak"""

s=input('Bir değer giriniz: ')
print(int(s)+1)

"""Çok satırlı karakter kümesi oluşturma"""

a='''Birden çok
satır olan 
bir metin'''
print(a)

"""Karakter kümelerinin işlenmesi"""

s="Bu bir metin"
print(s[0])

"""iki sayı alıp toplayan python kodu"""

a=int(input("İlk sayıyı giriniz: "))
b=int(input("İkinci sayıyı giriniz: "))
print(a+b)

"""Koşul yapıları"""

islem=input("Yapılacak işlemi giriniz: ")
if (islem=='+'):
  print(a+b)
elif (islem=="*"):
  print(a*b)
else:
  print("İşlem bilinmiyor!")

"""Formatlı print"""

print("%d + %d = %d"%(a,b,a+b))

print("{2} - {1} = {0}".format(a,b,a+b))
print("{0} + {1} = {2}".format(a,b,a+b))
print(f"{a} * {b} = {a*b}")
print(str(a)+" + "+str(b)+" = "+str(a+b))